from typing import Optional, Protocol

from ccxt.base.types import Balances, Int, OrderBook, Ticker


class Exchange(Protocol):
    """코드에 사용될 ccxt.Exchange의 메서드에 대한 프로토콜 정의(타입 확인용)"""

    def fetch_balance(self, params={}) -> Balances: ...
    def fetch_ticker(self, symbol: str, params={}) -> Ticker: ...
    def fetch_order_book(self, symbol: str, limit: Int = None, params={}) -> OrderBook: ...
    def set_sandbox_mode(self, enabled: bool) -> None: ...
    def load_markets(self, reload: bool = False) -> dict: ...
    def create_order(self, symbol: str, type: str, side: str, amount: float, price: Optional[float] = None, params={}) -> dict: ...
    def amount_to_precision(self, symbol: str, amount: float) -> str: ...
    def price_to_precision(self, symbol: str, price: float) -> str: ...

    @property
    def name(self) -> str: ...
    @property
    def id(self) -> str: ...
    @property
    def timeout(self) -> Optional[int]: ...
